version: "3.8"

services:
  board-service:
    container_name: batch-service
    image: ${DOCKER_USERNAME}/batch-service:latest
    ports:
      - "8085:8085"
    env_file:
      - .env
    networks:
      - backend

networks:
  backend:
    external: true