server:
  port: 8085

spring:
  application:
    name: batch-service
  profiles:
    active: dev

  batch:
    job:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EC2_HOST}:8761/eureka/

